#!/usr/bin/php
<?Php

use datagutten\tools\files\files;
use torrentupload\utils;

require $_composer_autoload_path ?? __DIR__ . '/../vendor/autoload.php';

$torrent_file = files::path_join(dirname($argv[1]), basename($argv[1])) . '.torrent';
$torrent = utils::buildtorrent($argv[1], $torrent_file);
printf("Torrent created as %s\n", $torrent);