#!/usr/bin/php
<?php
require $_composer_autoload_path ?? __DIR__ . '/../vendor/autoload.php';

use GetOpt\GetOpt;

$options = [['s', 'site', GetOpt::REQUIRED_ARGUMENT, 'Site name'],
    ['p', 'path', GetOpt::REQUIRED_ARGUMENT, 'File or folder to be uploaded'],
    ['c', 'category', GetOpt::REQUIRED_ARGUMENT, 'Torrent category']];

$upload = new torrentupload\upload($options);


$pathinfo = $upload->pathinfo();
$mediainfo = $upload->mediainfo();
$description = $upload->description();


$upload->login();

$file_torrent = $upload->torrent_file();
$args = ['torrentfile' => $file_torrent, 'description' => $description, 'title' => $pathinfo['filename'], 'mediainfo' => $mediainfo];

try
{
    $args['categories']=$upload->site->get_template($upload->getOpt->getOption('category'));
}
catch (FileNotFoundException $e)
{
    die('Invalid category ' . $upload->getOpt->getOption('category') . "\n");
}

try
{
    $torrent_url = $upload->upload();
    unlink($file_torrent);
    $upload->site->session->get($torrent_url, [], ['filename' => $file_torrent]);
    printf("Uploaded file saved as %s\n", $file_torrent);
}
catch (torrentupload\exceptions\UploadFailedException $e)
{
    printf("Upload failed: %s\n%s", $e->getMessage(), $e->getTraceAsString());
}